In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import BernoulliNB,MultinomialNB,GaussianNB 
#!pip install mixed-naive-bayes
#from mixed_naive_bayes import MixedNB
from sklearn.metrics import confusion_matrix
from sklearn import metrics

In [2]:
import os
os.chdir(r'C:\Users\Vish\Documents\Data\Dataset')
dataset = pd.read_csv('Iris.csv')

In [3]:
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
dataset.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [5]:
dataset.drop(['Id'],inplace=True,axis=1)

In [6]:
dataset.columns = ['sepal length in cm', 'sepal width in cm','petal length in cm','petal width in cm','species']

In [7]:
factor = pd.factorize(dataset['species'])
dataset.species = factor[0]
definitions = factor[1]
print(dataset.species.head())
print(definitions)

0    0
1    0
2    0
3    0
4    0
Name: species, dtype: int64
Index(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='object')


In [8]:
#Splitting the data into independent and dependent variables
X = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4].values
print('The independent features set: ')
print(X[:5,:])
print('The dependent variable: ')
print(y[:5])

The independent features set: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
The dependent variable: 
[0 0 0 0 0]


In [9]:
# Creating the Training and Test set from data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 21)

In [10]:
#Model building
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [11]:
#classifier = BernoulliNB()
#classifier = MultinomialNB()
#clf = MixedNB(categorical_features=[0,1])

In [12]:
#Predictions
# The predict fuction converts probability values > .5 to 1 else 0
y_pred = classifier.predict(X_test)

In [13]:
reversefactor = dict(zip(range(3),definitions))
y_test = np.vectorize(reversefactor.get)(y_test)
y_pred = np.vectorize(reversefactor.get)(y_pred)
print(pd.crosstab(y_test, y_pred, rownames=['Actual Species'], colnames=['Predicted Species']))

Predicted Species  Iris-setosa  Iris-versicolor  Iris-virginica
Actual Species                                                 
Iris-setosa                 13                0               0
Iris-versicolor              0               12               3
Iris-virginica               0                0              10


In [14]:
#Evaluating model
cm=metrics.confusion_matrix(y_test,y_pred)
print(cm)
metrics.accuracy_score(y_test,y_pred)

[[13  0  0]
 [ 0 12  3]
 [ 0  0 10]]


0.9210526315789473