In [1]:
import pandas as pd
import numpy as np
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import NearMiss
from sklearn.model_selection import train_test_split

In [2]:
import os
os.chdir(r'C:\Users\vish\Documents\Data\Dataset')
df=pd.read_csv("diabetes.csv")

In [3]:
df.shape

(768, 9)

In [4]:
df.Outcome.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [5]:
x=df.drop(['Outcome'],1).to_numpy()

In [8]:
x.shape

(768, 8)

In [9]:
y=df['Outcome'].to_numpy()

In [10]:
y.shape

(768,)

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=20)

In [17]:
np.bincount(y_train)

array([370, 206], dtype=int64)

In [15]:
sm=SMOTE() 
#default : k_neighbors=5 
x_train_smote,y_train_smote=sm.fit_resample(x_train,y_train)
np.bincount(y_train_smote) 

array([370, 370], dtype=int64)

In [16]:
nr=NearMiss()
#default : n_neighbors=3
x_train_nearmiss,y_train_nearmiss=sm.fit_resample(x_train,y_train)
np.bincount(y_train_nearmiss)

array([370, 370], dtype=int64)